name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull rakshitgarg99126/ci_cd_practice:latest
    - name: Delete Old Docker container
      run: sudo docker rm -f ci_cd_practice-container || true
    - name: Run Docker container
      run: sudo docker run -d -p 8080:8080 --name ci_cd_practice-container rakshitgarg99126/ci_cd_practice
