name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log In to dockerHub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

    - name: Build docker image
      run: docker build -t ci_cd_practice .
    - name: Tag image docker
      run: docker tag ci_cd_practice:latest rakshitgarg99126/ci_cd_practice:latest
    - name: push docker image
      run: docker push rakshitgarg99126/ci_cd_practice:latest
